Cassie Lee/week5/day3/architects/config/routes.rb
Rails.application.routes.draw do
 
  get 'architecture/new'
  get 'architecture/create'
  get 'architecture/index'
  get 'architecture/show'
  get 'architecture/edit'
  get 'architecture/update'
  get 'architecture/destroy'
  root to: 'pages#home'

  get '/architects/new' => 'architects#new', as: 'new_architect'

  post '/architects' => 'architects#create'


  get '/architects' => 'architects#index'

  get '/architects/:id' => 'architects#show', as: 'architect'
  
  get 'architects/:id/edit' => 'architects#edit', as: 'edit_architect'

  patch '/architects/:id' => 'architects#update'

  delete '/architects/:id' => 'architects#destroy'


resources :works




end

Cassie Lee/week5/day3/architects/app/models/architect.rb
class Architect < ApplicationRecord
    has_many :architectures


end

Cassie Lee/week5/day3/architects/app/models/architecture.rb
class Architecture < ApplicationRecord
end

Cassie Lee/week5/day3/architects/app/controllers/architects_controller.rb
class ArchitectsController < ApplicationController
  def new
    @architect = Architect.new
  end

  def create
    Architect.create architect_params

    redirect_to architects_path
  end

  def index
    @architects = Architect.all
  end

  def show
    @architect = Architect.find params[:id]
  end

  def edit
    @architect = Architect.find params[:id]
  end

  def update
    architect = Architect.find params[:id]
    architect.update architect_params

    redirect_to architect_path( params[:id])
  end

  def destroy
    Architect.destroy params[:id]
    redirect_to architect_path
  end


  private

  def architect_params
    params.require(:architect).permit(:name, :dob, :nationality, :image)

  end


end

Cassie Lee/week5/day3/architects/app/controllers/architecture_controller.rb
class ArchitectureController < ApplicationController
  def new
  end

  def create
  end

  def index
    @architectures = Architecture.all
  end

  def show
    @architecture = Architecture.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

Cassie Lee/week5/day3/architects/app/helpers/architecture_helper.rb
module ArchitectureHelper
end

Cassie Lee/week5/day3/architects/app/helpers/artists_helper.rb
module ArtistsHelper
end

Cassie Lee/week5/day3/architects/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Architects</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
  </head>

  <body>
    <header>
      <nav>
      <h1>Architects</h1>
      <%= link_to 'Architects', architects_path %>
      <%= link_to 'Add Architects', new_architect_path %>
      <%= link_to 'Architectures', architectures_path %>




      </nav>
    </header>
    <%= yield %>
  </body>
</html>