Daniel Lord-Doyle/week5/pokemon-db/config/routes.rb
Rails.application.routes.draw do

  root to: 'owners#index'

  resources :owners, :pokemons

end

Daniel Lord-Doyle/week5/pokemon-db/app/models/owner.rb
class Owner < ApplicationRecord

    has_many :pokemons

end

Daniel Lord-Doyle/week5/pokemon-db/app/models/pokemon.rb
class Pokemon < ApplicationRecord

    belongs_to :owner

end

Daniel Lord-Doyle/week5/pokemon-db/app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    Owner.create owner_params
    redirect_to owners_path
  end

  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find params[:id]
    @pokemon = Pokemon.all
  end

  def edit
    @owner = Owner.find params[:id]
  end

  def update
    owner = Owner.find params[:id]
    owner.update owner_params

    redirect_to owner_path
  end

  def destroy
    Owner.destroy params[:id]
    redirect_to owners_path
  end

  private 
  
  def owner_params
    params.require(:owner).permit(:name,:age,:hometown,:pokemon_owned, :champion, :image)
  end


end

Daniel Lord-Doyle/week5/pokemon-db/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def new
    @pokemon = Pokemon.new
  end

  def create
    Pokemon.create pokemon_params
    redirect_to pokemons_path
  end

  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find params[:id]
  end

  def edit
    @pokemon = Pokemon.find params[:id]
  end

  def update
    pokemon = Pokemon.find params[:id]
    pokemon.update pokemon_params

    redirect_to pokemon_path
  end

  def destroy
    Pokemon.destroy params[:id]
    redirect_to pokemons_path
  end

  private 
  
  def pokemon_params
    params.require(:pokemon).permit( :name,:level,:special_move,:image,:owner_id )
  end

end

Daniel Lord-Doyle/week5/pokemon-db/app/helpers/owners_helper.rb
module OwnersHelper
end

Daniel Lord-Doyle/week5/pokemon-db/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

Daniel Lord-Doyle/week5/pokemon-db/app/views/pokemons/_form.html.erb
<%= form_with model: @pokemon, local: true do |f| %>

    <%= f.label :name  %>
    <br>
    <%= f.text_field :name %>
    <br><br>

    <%= f.label :level  %>
    <br>
    <%= f.text_field :level %>
    <br><br>

    <%= f.label :special_move  %>
    <br>
    <%= f.text_field :special_move %>
    <br><br>

    <%= f.label :image  %>
    <br>
    <%= f.text_field :image %>
    <br><br>

  <%= f.label :owner_id %>
  <br>
  <%= f.collection_select :owner_id, Owner.all, :id, :name %>
  <br><br>

<%= f.submit %>

<% end %>

      <%# t.string :name
      t.string :description
      t.string :image_one
      t.string :image_two
      t.integer :pokedex_no
      t.string :pokemon_type
      t.integer :gender_ration
      t.integer :catch_rate
      t.float :height
      t.float :weight
      t.string :ability_one
      t.string :ability_two
      t.string :ability_three
      t.string :ability_four
      t.integer :owner_id %>

Daniel Lord-Doyle/week5/pokemon-db/app/views/pokemons/edit.html.erb
<h1>Edit <%= @pokemon.name %></h1>

<%= render partial: 'form' %>

Daniel Lord-Doyle/week5/pokemon-db/app/views/pokemons/index.html.erb
<h2>Index of Pokemon</h2>

<ul class="pokemonUL">

    <% @pokemons.each do |pokemon| %>
        <li>
            <%= link_to image_tag(pokemon.image_one), pokemon_path(pokemon.id)  %>
        </li>
    <% end %>

</ul>

Daniel Lord-Doyle/week5/pokemon-db/app/views/pokemons/new.html.erb
<h1>Catch a New Pokemon</h1>

<%= render partial: 'form' %>

Daniel Lord-Doyle/week5/pokemon-db/app/views/pokemons/show.html.erb
<h2> <%= @pokemon.name %> </h2>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %>
<%= link_to 'Delete', pokemon_path(@pokemon), method: 'delete' %>
<br>
<% if @pokemon.image_one.present? %>
    <%= image_tag @pokemon.image_one, alt: @pokemon.name, class: 'pokemon_image' %>
<% end %>
<% if @pokemon.image_two.present? %>
    <%= image_tag @pokemon.image_two, alt: @pokemon.name, class: 'pokemon_image' %>
<% end %>

<p>
    <strong>Description: </strong> <%= @pokemon.description %>
</p>

<p>
    <strong>Pokédex No.: </strong> <%= @pokemon.pokedex_no %>
</p>

<p>
    <strong>Gender Ration: </strong> <%= @pokemon.gender_ration %>%
</p>
<p>
    <strong>Catch Rate: </strong> <%= @pokemon.catch_rate %>%
</p>
<p>
    <strong>Height: </strong> <%= @pokemon.height %>
</p>
<p>
    <strong>Weight: </strong> <%= @pokemon.weight %>
</p>
<p>
    <strong>Ability 1: </strong> <%= @pokemon.ability_one %>
</p>
<p>
    <strong>Ability 2: </strong> <%= @pokemon.ability_two %>
</p>
<p>
    <strong>Ability 3: </strong> <%= @pokemon.ability_three %>
</p>
<p>
    <strong>Ability 4: </strong> <%= @pokemon.ability_four %>
</p>