Angela Zhang/week5/haunted-places-db/config/routes.rb
Rails.application.routes.draw do
  
  #CREATE
  # 1. BLANK FORM
  get '/places/new' => 'places#new', as: 'new_place'

  # 2. SUBMIT FORM
  post '/places/' => 'places#create'


  #READ
  # HOMEPAGE

   root to: 'places#home'

  # haunted PLACES INDEX

  get '/places' => 'places#index'

  get '/places/:id' => 'places#show', as: 'place'


  #UPDATE
  # 1.PRELOADED FORM
  get '/places/:id/edit' => 'places#edit', as: 'edit_place'

  # 2.SUBMIT EDIT FORM
  patch 'places/:id' => 'places#update'

  #DELETE
  get '/places/:id/delete' => 'places#destroy', as: 'destroy_place'

  
end

Angela Zhang/week5/haunted-places-db/app/models/place.rb
class Place < ApplicationRecord


end

Angela Zhang/week5/haunted-places-db/app/controllers/places_controller.rb
class PlacesController < ApplicationController
    def home
    end

    def new
        @place =Place.new
    end

    def create 
        Place.create(
            name: params[:place][:name],
            location: params[:place][:location],
            built: params[:place][:built],
            ghosts_num: params[:place][:ghosts_num],
            ghost_name: params[:place][:ghost_name],
            ghost_description: params[:place][:ghost_description],
            image_url: params[:place][:image_url]
        )
        redirect_to places_path
    end

    def index
        @places = Place.all
    end

    def show
        @place = Place.find params[:id]
    end

    def edit 
        @place = Place.find params[:id]
    end

    def update 
        place = Place.find params[:id]

        place.update(
            name: params[:place][:name],
            location: params[:place][:location],
            built: params[:place][:built],
            ghosts_num: params[:place][:ghosts_num],
            ghost_name: params[:place][:ghost_name],
            ghost_description: params[:place][:ghost_description],
            image_url: params[:place][:image_url]
            )
        redirect_to place_path( params[:id] )
    end

    def destroy 
        Place.destroy params[:id]
        redirect_to places_path
    end

end # class

Angela Zhang/week5/haunted-places-db/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haunted Places</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav>
      <h1>FAMOUS HAUNTED PLACES</h1>
      <%= link_to 'Home', root_path %> 
      |
      <%= link_to 'Haunted Places', places_path %> 
      |
      <%= link_to 'Add New Place', new_place_path %> 

      
      <hr>
    </nav>

    <%= yield %>

    <footer>
      &copy; Haunted Places - Angela Zhang 2022
    </footer>
  </body>
</html>

Angela Zhang/week5/haunted-places-db/app/views/places/edit.html.erb
<h2>Edit Place: <%= @place.name %></h2>

<!-- NOT VERY DRY to copy-paste this entire identical form from new.html.erb,tomorrow we'll use 'render'-->
<%= form_with model: @place, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <%= f.label :built %>
    <%= f.text_field :built %> 
    <br>
    <%= f.label :ghosts_num %>
    <%= f.text_field :ghosts_num %>  
    <br>
    <%= f.label :ghost_name %>
    <%= f.text_field :ghost_name %>  
    <br>
    <%= f.label :ghost_description %>
    <%= f.text_field :ghost_description %>  
    <br>
    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url %> 
    <br>

    <%= f.submit %>

<% end %>

Angela Zhang/week5/haunted-places-db/app/views/places/home.html.erb
<h1>The Most Haunted Places</h1>

<img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/haunted-hb-promo-v01-1538175389.png" alt="Creepy Haunted Place">

Angela Zhang/week5/haunted-places-db/app/views/places/index.html.erb
<h1>HAUNTED PLACES INDEX</h1>

<ul>
    <% @places.each do |place| %>
        <li>
            <%= link_to place.name, place_path(place.id) %> 
        </li>
    <% end %>
</ul>

Angela Zhang/week5/haunted-places-db/app/views/places/new.html.erb
<h2>Add a new haunted place</h2>


<%= form_with model: @place, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <br>
    <%= f.label :built, "Year built" %>
    <%= f.text_field :built %> 
    <br>
    <%= f.label :ghosts_num, "Number of known Ghost" %>
    <%= f.text_field :ghosts_num %>  
    <br>
    <%= f.label :ghost_name, "Notorious Ghost's Name" %>
    <%= f.text_field :ghost_name %>  
    <br>
    <%= f.label :ghost_description %>
    <%= f.text_field :ghost_description %>  
    <br>
    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url %> 
    <br>

    <%= f.submit "Add Place" %>

<% end %>

Angela Zhang/week5/haunted-places-db/app/views/places/show.html.erb
<h2><%= @place.name %></h2>

<%= link_to 'Edit', edit_place_path(@place.id) %>
<%= link_to 'Delete', destroy_place_path(@place.id) %>


<p>
<strong>Location: </strong>
<%= @place.location %>
</p>

<p>
<strong>Built: </strong>
<%= @place.built %>
</p>

<p>
<strong>Number of known Ghosts: </strong>
<%= @place.ghosts_num %> 
</p>

<p>
<strong>Notorious Ghost: </strong>
<%= @place.ghost_name %>
</p>
<p>
<strong>Description/Activity: </strong>
<%= @place.ghost_description%> 
</p>

<%= image_tag @place.image_url, alt: @place.name %>