Laurence Qi/week5/day4/hr-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies
  resources :employees
  
end

Laurence Qi/week5/day4/hr-app/app/models/company.rb
class Company < ApplicationRecord
end

Laurence Qi/week5/day4/hr-app/app/models/employee.rb
class Employee < ApplicationRecord
end

Laurence Qi/week5/day4/hr-app/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    Company.create company_params
    # pass in the company params, and create
    redirect_to companies_path
  end

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find params[:id]
  end

  def edit
    @company = Company.find params[:id]
  end

  def update
    work = Company.find params[:id]
    work.update! company_params
    redirect_to company_path(params[:id])
  end

  def destroy
    Company.find(params[:id]).destroy    

    redirect_to companies_path
  end

  private def company_params 
    params.require(:company).permit(:name, :industry, :revenue)
  end
end

Laurence Qi/week5/day4/hr-app/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.create
  end

  def create
    Employee.create employee_params
  end

  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find params[:id]
  end

  def edit
    @employee = Employee.find params[:id]
  end

  def update
    employee = Employee.find params[:id]
    employee.update! employee_params
  end

  def destroy

  end

  private def employee_params

    
  end
end

Laurence Qi/week5/day4/hr-app/app/helpers/companies_helper.rb
module CompaniesHelper
end

Laurence Qi/week5/day4/hr-app/app/helpers/employees_helper.rb
module EmployeesHelper
end

Laurence Qi/week5/day4/hr-app/app/views/companies/_form.html.erb
<%= form_with model: @company, local: true do |f| %>

    <div><%= f.label :name %></div>
    <div><%= f.text_field :name %></div>
    <br>

    <div><%= f.label :industry %></div>
    <div><%= f.text_field :industry %></div>
    <br>

    <div><%= f.label :revenue %></div>
    <div><%= f.text_field :revenue %></div>
    <br>
    <div><%= f.submit %></div>
    
<% end %>

Laurence Qi/week5/day4/hr-app/app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

Laurence Qi/week5/day4/hr-app/app/views/companies/edit.html.erb
<h3>Editing <%= @company.name %></h3>
<%= render partial: 'form' %>

Laurence Qi/week5/day4/hr-app/app/views/companies/index.html.erb
<h3>All companies</h3>



<ul>
    <% @companies.each do |company|%>
        <li>
            <%= link_to company.name, company_path(company.id) %>
        </li>
    <% end %>
</ul>

Laurence Qi/week5/day4/hr-app/app/views/companies/new.html.erb
<h3>New company</h3>
<%= render partial: 'form' %>

Laurence Qi/week5/day4/hr-app/app/views/companies/show.html.erb
<h3><%= @company.name + ' Details' %></h3>
<%= link_to 'Edit', edit_company_path %>
<%= link_to 'Delete', company_path(@company.id), method: 'delete'%>
<p>Industy: <%= @company.industry %></p>
<p>Revenue(millions): $<%= @company.revenue %></p>